### ISSUE TITLE
long term architecture / roadmap

### ISSUE THREAD

**Issue by lytico** [dotdevelop/community#9]
discussions about architecture

**Comment by lytico** [comment]
suggestions from an insider (sender is known, but i don't want to make her/him public):
> For the editor layer I would recommend switching back to an older version and start from there.
> The visual studio infrastructure is not required and a problem.
> I would suggest moving roslyn out of process like vscode and be flexible in the data structures the IDE uses and stick to the best/most efficient solution.
> In general I would suggest cutting down features. Remove everything you think you don't need and add stuff as required.
> For example: VCS support ? Mac related code etc.

**Comment by lextm** [comment]
In fact, a few things I recommend,

- [ ] Revive 7.x release as that provides a stable starting point. I already have everything ready for Windows port, while I believe the Linux port is easy too.
- [ ] Take over homepage/brands/Linux package repo and other assets from Microsoft/Xamarin, so the community can release future releases under MonoDevelop name.
- [ ] Plan out future releases.

A few important things (as the last comment said) should be included in the roadmap,

* Language server protocol support, so that Roslyn/OmniSharp can be integrated. Then MonoDevelop shares the same backend like VSCode.
* Debugger adapter protocol support, and take over Samsung's .NET Core debugger. The former is already there in 8.x, so just need to be back ported. The latter hasn't been updated by Samsung for a while and is buggy on Debugger adapter protocol support. Once this is done, .NET Core support can be completed, and gives a solid ground for other tasks.
* Evaluate new things done in 8.x releases and see how much can be reused.

**Comment by lytico** [comment]
Release 8.6 preview see here: #10

**Comment by lytico** [comment]
@lextm please make a suggestion which 7.x we should fork.
lastest 7.8 release was from here: https://github.com/mono/monodevelop/tree/monodevelop-7.8.4.1 , as far as i can see.

**Comment by lextm** [comment]
@lytico Use `release-7.8` branch is better. 7.8.4.1 is the last tag on that branch, which is the last release for 7.x.

**Comment by FlaviusHouk** [comment]
> suggestions from an insider (sender is known, but i don't want to make her/him public):
> 
> > For the editor layer I would recommend switching back to an older version and start from there.
> > The visual studio infrastructure is not required and a problem.
> > I would suggest moving roslyn out of process like vscode and be flexible in the data structures the IDE uses and stick to the best/most efficient solution.
> > In general I would suggest cutting down features. Remove everything you think you don't need and add stuff as required.
> > For example: VCS support ? Mac related code etc.

That sounds pretty well.
It would be quite well to work in the core IDE with general data structures not related to any particular language or tool. It will allow to work with any other tools for language analysis (maybe even not dotnet).
